### PR TITLE
Fix tests in master, upgrade all dependencies in prep for v2.0.

### LINKED ISSUE #19: Master build is failing
This seems to have been the case since #17 was merged.

### LINKED ISSUE #20: Icicle does not work on Redis >= 3.0
Because of a change in the names of the logging levels in Redis Lua, Icicle does not work on Redis >= 3.0.

The logging level of `LOG_INFO` has been renamed to `LOG_NOTICE`, causing the Lua script to fail hard.

### PR DESCRIPTION
**Pull request by nathankleyn**
This fixes #19, and gets us one step closer to cutting the v2.0 release
because we are now working on Redis v3.0+, which fixes #20.

### CODE REVIEW

**Comment by nathankleyn** [comment]
(Pinging @maciekciolek who will want this fix to use Icicle on Redis >= 3.0. 😀 )

File: project/commons.scala [hunk 1]
```diff
@@ -26,15 +26,15 @@ object Commons {
...
+    scalaVersion := "2.11.8",
     organization := "com.intenthq.icicle",
     version := appVersion,
     publishMavenStyle := true,
     crossPaths := false,
     autoScalaLibrary := false,
     publishArtifact in Test := false,
     pomIncludeRepository := { _ => false },
-    resolvers += "Scalaz Bintray Repo" at "https://dl.bintray.com/scalaz/releases",
+    // resolvers += "Scalaz Bintray Repo" at "https://dl.bintray.com/scalaz/releases",
```
Comment (nathankleyn) [inline project/commons.scala]: I will remove this, was a test and forgot to take it out!

Comment (nathankleyn) [inline project/commons.scala]: Fixed! 👍
